//https://discord.js.org/#/docs/main/stable/class/Permissions?scrollTo=s-FLAGS
const utils = require(__dirname  + '/utils.js');

const commandList = {
  'help':{
    description: 'You\'re lookin\' at it.',
    call: (message) => {
      let embed = {
        "title": "Available Commands:",
        "color": 7729478,
        'fields': []
      };

      for (const command in commandList){
        if(utils.checkPermissions(message, commandList[command].requiredPermissions)){
          embed.fields.push({'name': command, 'value': commandList[command].description});
        }
      }
      let reactionsString = '';
      for (const react in reactions){
        reactionsString += ` ${react}\n`;
      }
      let reactionsField = {
        'name': 'reactions',
        'value': `the following commands will reply with a random reaction based on the given keyword.\n\`\`\`\n ${reactionsString} \`\`\``;
      }
      embed.fields.push(reactionsField)
      message.reply('', {embed});
    },
  },
  'ping':{
    description: 'pong!',
    call: (message) => {message.reply('Pong!');}
  },
  'setgame':{
    description: 'set\'s the game I play!',
    requiredPermissions: ['ADMINISTRATOR'],
    call: (message) => {
      const gameList = [
        "Tetris or something",
        "Pong or something",
        "Something funny in binary",
        ":(){ :|:& };:",
        "Cool kids use me.",
        "//Autogenerated",
        "Worlds #0 discord bot.",
        "TODO: write something clever.",
        "Half life 3",
        "skynet.exe",
        "With your harddrive",
        "With your bits",
        "With your bytes",
        "Destroy all humans",
        "hello world!",
        "rm -rf /",
        "feature",
        "git push --force",
        "for(;;)",
        "#define true (math.rand() > 0.5)",
        ""
      ];

      const gameName = utils.getRandomItem(gameList);
      console.log(gameName);
      message.client.user.setPresence({game:{name:gameName}});
    },
  },
  'addreaction':{
    description: `adds a new reaction option\n usage: !addreaction [keyword] [reaction text/image]`,
    requiredPermissions: ['ADMINISTRATOR'],
    call: (message) => {
      const key = message.content.split(' ')[1].slice(prefix.length).toLowerCase();
      const reaction = message.content.split(key)[1];
      reactions[key].push(reaction);
      utils.writeJSON('reactions.json', reactions);
    }
  }
};

module.exports = commandList;
// export default commandList;