"use strict";
let Discord   = require("discord.js");
let owStats   = require('./owStats.js');
let gameRoles = require('./gameRoles.js');
let logger    = require('./logger.js');
let colors    = require('colors/safe');

let bot = global.bot;

let Commands = {
        "help":{
            description: "You're lookin' at it.",
            call: function(message, args){ helpMessageFunc(message, args)},
        },
        "owStat":{
            description: "get overbuff page for a user. \n" +
                         "use @user to request a given user.\n" +
                         "use set bnet#0000 to link your account.\n" +
                         "linking you account will update your overbuff page daily!",
            call: function(message, args){ owStats.owStats(message, args)},
        },
        "role":{
            description: "!role join -  join the role!\n" +
                         "!role leave - leave the role!\n" +
                         "!role list - list the members!",
            call: function(message, args){ gameRoles.gameRole(message, args)},
        },
        "game":{
            description: "move you and players to apropriate voice channel (WIP)",
            permissionsReq: {voiceMoveMembers: true},
            call: function(message, args){ moveUsersToGame(message, args)},
        },
        "ping":{
            description: "pong",
            permissionsReq: {administrator: true},
            call: function(message, args){
                bot.sendMessage(message, "!pong");
                logger.log("!pong");
                return true;
            },
        },
        "updateOW":{
            description: "forces update of overbuff pages",
            permissionsReq: {administrator: true},
            call: function(message, args){ owStats.updateOwStats(message, args)},
        },
        "setGame":{
            description: "set's the game I play!",
            permissionsReq: {administrator: true},
            call: function(message, args){
                let gameList = [
                    "Tetris or something",
                    "Pong or something",
                    "Something funny in binary",
                    ":(){ :|:& };:",
                    "Cool kids use me.",
                    "//Autogenerated",
                    "Worlds #0 discord bot.",
                    "TODO: write something clever.",
                    "Half life 3",
                    "skynet.exe",
                    "With your harddrive",
                    "With your bits",
                    "With your bytes",
                    "Destroy all humans",
                    "hello world!",
                    "rm -rf /",
                    "feature",
                    "git push --force",
                    "for(;;)",
                    "#define true (math.rand() > 0.5)",
                    ""
                ];
                if(args){
                    args = args.toString();
                }else{
                    args = gameList[Math.trunc(Math.random()*gameList.length)];
                }

                try{
                    logger.log(message.author.id);
                }catch(err){
                    logger.error(err);
                }
                logger.log("setGame: ");
                logger.log(args);
                let flag = true;

                bot.setPlayingGame(args, function(err) {
                    if (err) {
                        logger.error(err, err);
                        flag = false;
                    }
                });

                return flag;
            },
        },
        "!color":{
            description: "lets you send a message in a given text color",
            permissionsReq: {administrator: true},
            call: function (message) {
                let languageList = logger.langList;
                for (var i = 0; i < languageList.length; i++) {
                    let testText = "```" + languageList[i] + "\n" +
                                   "test test test" + languageList[i] + "\n" +
                                   "test test test\n" +
                                   "```\n";
                    bot.sendMessage(message, testText);
                }
            }
        },
};

function helpMessageFunc(message, args) {
    logger.log(message.content);
    logger.log(args);
    let helpMessage = "";
    if(!args){
        for (var command in Commands) {
            if (checkPermissions(message, message.author, Commands[command].permissionsReq)) {
                helpMessage += "!" + command + " -\n";
                if(Commands[command].description){
                    helpMessage += "``` " + Commands[command].description + " ```\n";
                }
            }
        }
    }
    else{
        for (var i = 0; i < args.length; i++) {
            if(Commands[args[i]] &&
                checkPermissions(message, message.author, Commands[args[i]].permissionsReq))
            {
                helpMessage += "!" + args[i] + " -\n";
                if(Commands[args[i]].description){
                    helpMessage += "```" + Commands[args[i]].description + "```\n";
                }
            }
            else{
                helpMessage += "invalid command!";
            }
        }
    }

    bot.sendMessage(message.channel, helpMessage);
    return true;
};

/**
 * checks if user has permissions for a command based on role level.
 */
function checkPermissions(message, user, roleOrPermList) {
    logger.log("checkPermissions");
    if(!roleOrPermList){
        logger.log("no roleOrPermList");
        return true;
    }
    if(!user){
        logger.log("no user");
        logger.log(new Error().stack);
        return false;
    }

    if(typeof(user) === "string"){
        user = message.server.users.get("id", user);
    }
    let userPerms = message.channel.permissionsOf(user);

    if(!user){
        throw new Error("invalid user.");
        logger.log(new Error().stack);
        return false;
    }

    let PERM_LIST = Discord.Constants.Permissions;

    for(var perm in PERM_LIST){
        let reqPerm  = roleOrPermList[perm];
        let userPerm = userPerms.hasPermission(PERM_LIST[perm]);

        if(roleOrPermList.hasPermission){
            reqPerm = roleOrPermList.hasPermission(PERM_LIST[perm]);
        }

        if(!!reqPerm && !userPerm){
            logger.log("  user did not have perm: ");
            logger.log(perm);
            return false;
        }
    }

    return true;
};

/**
 * Moves all users who are playing same game as author, to voice channel of that name.
 *     todo:move to more apropriate location
 *
 * @param  {Message} message Message containing "!game"
 */
function moveUsersToGame(message) {
    let messageToSend = ""; // message to send in response
    let game          = message.author.game; // game user is playing
    let server        = message.server;

    if (game !== null) {

        messageToSend += message.author + " is currently playing: " + game.name + "\n";
        messageToSend += "These players are  playing " + game.name + ":\n";
        messageToSend += "```" + "\n";
        let userList = [];
        for (var i = 0; i < server.members.length; i++) {
            if(server.members[i].game){
                if(game.name === server.members[i].game.name){
                    userList.push(server.members[i]);
                    messageToSend += server.members[i].name + "\n";
                }
            }
        }

        messageToSend += "```" + "\n";

        let gameChannels = server.channels.getAll("name", game.name.toLowerCase());
        let gameChannel  = gameChannels.get("type",
            "voice");
        if (gameChannel !== null) {
            messageToSend += "I found this channel: `" + gameChannel.name + "`\n";
            for (let i = 0; i < userList.length; i++) {
                bot.moveMember(userList[i], gameChannel, (function(err) {
                    if (err) logger.error(err, err);
                }));
            }
        }
    } else {
        messageToSend = message.author + " is not playing anything.";
    }

    bot.sendMessage(message, messageToSend);
};

this.Commands = Commands;
this.checkPermissions = checkPermissions;
